management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.info.env.enabled=true
info.app.name=testapp
info.anyproperty.value.version=v1
